- package.json
- screwdriver.yaml
Add screwdriver.yaml and update package.json
> Add screwdriver integration

- README.md
- package.json
BREAKING CHANGE: updates to v2
> Beta to master

- README.md
- package.json
> Changed version

- stories/buttons.stories.js
Have added Buttons documentation to the storybook
Functionalities covered:
Arg types : text & Icons
properties:  style, active, disabled, full, button text, button size, inverse, icon name, icon size, icon only.
> Storybook buttons

- stories/buttons.stories.js
- stories/modal.stories.js
- stories/progress.stories.js
Adding Modal and Progress documentation to CSS Storybook
> Storybook Modal & Progress

- stories/shadows.stories.js
- stories/tooltip.stories.js
Shadows and Tooltips Documentation for CSSnStorybook
---
**Before**
There were no Shadows and Tooltip components before
**After**
Tooltip:
Shadow:
---
> PR 1/2: Storybook documentation for Shadows and Tooltip

- stories/Navbar/navbarElements.stories.js
- stories/Navbar/navbarPlayground.stories.js
- stories/Navbar/navbarSections.stories.js
CSS Documentation for Navbar
component didn't exist before
**After**
hierarchy:
Playground nav inactive:
Playground nav active:
Nav bar elements (ex: background modifier):
Nav bar section (ex: center):
---
> CSS Documentation for Navbar

- package-lock.json
- package.json
- screwdriver.yaml
This PR updates semantic release and now matches the [denali-design/denali-ember](https://github.com/denali-design/denali-ember) process.
---
**Before**
N/A
**After**
N/A
---
> build: Update semantic release

- stories/Controls/checkbox.stories.js
- stories/Controls/radio.stories.js
- stories/Controls/toggle.stories.js
- stories/menu.stories.js
Storybook documentation for Menu and Selection control items (Radio, checkbox & Toggle)
---
Before:
no such components existed
After:
Heirarchy:
Menu:
Menu Right:
Radio:
Default: 
Radio group: 
Checkbox:
Default: 
Checkbox group:
Toggle:
Default:
Toggle group:
---
> Storybook documentation for menu and selection controls

- stories/Controls/toggle.stories.js
---
**Before**
Toggle label text wasn't a knob
**After**
---
> added knob for Toggle on/off text

- stories/fields.stories.js
- stories/tabs.stories.js
- stories/toggle.stories.js
Sprint 7 CSS Storybook documentation: (Fields, Tabs, Toggle)
---
**Before**
No such components existed
**After**
Fields:
Tabs:
Toggle:
---
> Sprint 7 CSS Storybook documentation: (Fields, Tabs, Toggle)

- stories/select.stories.js
- stories/sidebar.stories.js
CSS Documentation of Sidebar and Select components
---
**Before**
No such components existed
**After**
Components : Select and Side bar
Component 1: Select:
Default - no knobs:
Playground:
Component 2: Sidebar
Default - no knobs
Playground:
---
> sidebar and select documentation CSS

- README.md
- stories/guides/Theming.stories.mdx
Updated readme
---
**Before**
N/A
**After**
N/A
---
> Updated readme

- screwdriver.yaml
---
**Before**
N/A
**After**
N/A
---
> ci: run `npm ci` in publish job

- .storybook/DenaliTheme.js
- stories/Navbar/navbarElements.stories.js
---
**Before**
N/A
**After**
N/A
---
> docs: fix storybook logo paths for gh-pages

- stories/guides/Installation.stories.mdx
---
**Before**
N/A
**After**
N/A
---
> docs: update installation text

- stories/guides/Theming.stories.mdx
Added a theming guide.
---
---
> docs: Update Theming.stories.mdx

- scss/components/breadcrumb.scss
- scss/utilities/root-variables.scss
Add breadcrumb active state is-active with bold font and grey color and related root variables.
---
**Before**
**After**
---
> Breadcrumb: Active State

- scss/helpers/misc.scss
Helpers: Background Image Classes #157 
---
> Helpers: Background Image

- screwdriver.yaml
Fix the publish job
**Before**
N/A
**After**
N/A
---
> build: don't shallow git clone when publishing

- .storybook/preview.js
- css/denali-dark-theme.css
- scss/resets/denali-reset.scss
- stories/guides/Variables.stories.mdx
---
**Before**
N/A
**After**
N/A
---
> Updates to parent class while theming

- CHANGELOG.md
publish accordion & margin helpers
**Before**
N/A
**After**
N/A
---
> feat: publish accordion & margin helpers

- css/denali-components.css
- css/denali-dark-theme.css
- css/denali.css
- scss/components/table.scss
Fixes table sort icons not rendering
---
**Before**
**After**
---
> fix: table sort icons not rendered

- screwdriver.yaml
fix docs deploy
**Before**
N/A
**After**
N/A
---
> ci: fix docs deploy
